name: BitcoinAIWallet
options:
  bundleIdPrefix: com.bitcoinai
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: "88VBQWB9K5"
    CODE_SIGN_STYLE: "Automatic"
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
    INFOPLIST_KEY_NSFaceIDUsageDescription: "Authenticate to access your wallet"
    INFOPLIST_KEY_NSCameraUsageDescription: "Scan QR codes to receive Bitcoin addresses"
    INFOPLIST_KEY_CFBundleDisplayName: "Bitcoin Wallet"
    GENERATE_INFOPLIST_FILE: YES
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  BitcoinAIWallet:
    type: application
    platform: iOS
    sources:
      - path: BitcoinAIWallet
        excludes:
          - "Package.swift"
    resources:
      - path: BitcoinAIWallet/Assets.xcassets
      - path: BitcoinAIWallet/Localization/en.lproj
        buildPhase: resources
      - path: BitcoinAIWallet/Localization/ar.lproj
        buildPhase: resources
      - path: BitcoinAIWallet/Localization/es.lproj
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bitcoinai.wallet
        PRODUCT_NAME: "Bitcoin AI Wallet"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
    info:
      path: BitcoinAIWallet/Info.plist
      properties:
        CFBundleDisplayName: "Bitcoin Wallet"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        UIBackgroundModes:
          - fetch
    entitlements:
      path: BitcoinAIWallet/BitcoinAIWallet.entitlements
      properties:
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.bitcoinai.wallet"

  BitcoinAIWalletTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: BitcoinAIWallet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bitcoinai.wallet.tests
